# Generated by Django 3.0 on 2021-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='write title about your service', max_length=200)),
                ('content', models.TextField(help_text='write in detail about your service')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('classtimestart', models.CharField(help_text='When childfinish there class', max_length=7, null=True)),
                ('classtimefinish', models.CharField(help_text='When childstart there class', max_length=7, null=True)),
                ('childagestart', models.CharField(help_text='When childagestart there class', max_length=2, null=True)),
                ('childagefinish', models.CharField(help_text='When childagefinish there class', max_length=2, null=True)),
                ('price', models.IntegerField(blank=True, help_text='class/service fee', null=True)),
                ('durationofclass', models.IntegerField(blank=True, help_text='how long child stay in class in a day', null=True)),
            ],
        ),
    ]
