# Generated by Django 3.0 on 2021-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('out', models.DateTimeField(help_text='When childfinish there class', null=True)),
                ('_in', models.DateTimeField(help_text='When childstart there class', null=True)),
                ('childagestart', models.DateTimeField(help_text='When childagestart there class', null=True)),
                ('childagefinish', models.DateTimeField(help_text='When childagefinish there class', null=True)),
            ],
        ),
    ]
