# Generated by Django 3.0 on 2021-12-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20211214_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='classtimefinish',
            field=models.CharField(blank=True, help_text='When childstart there class', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='classtimestart',
            field=models.CharField(blank=True, help_text='When childfinish there class', max_length=7, null=True),
        ),
    ]
