# Generated by Django 3.2 on 2022-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20220331_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='features_images')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
            ],
        ),
    ]
