# Generated by Django 3.2 on 2022-03-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nid',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
