# Generated by Django 3.2 on 2022-03-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_contact_service_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_choice', models.CharField(blank=True, choices=[('HO', 'Hostel'), ('HA', 'Halfday'), ('FD', 'Fullday'), ('AS', 'After-school'), ('HD', 'Holiday'), ('NS', 'Night-stay')], max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service_choice',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Servicesname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.service_add'),
        ),
    ]
