# Generated by Django 3.2 on 2022-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20220331_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_add',
            name='service_choice',
        ),
        migrations.AddField(
            model_name='service_add',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
